# chainlens development tasks.
#
# PYTHONPATH is deliberately emptied for every target.
#
# Rationale: a contributor's shell may have unrelated site-packages on
# PYTHONPATH — e.g. a sourced ROS 2 workspace, a conda env, another project's
# install tree. pytest auto-loads every `pytest11` entry point it can see, so
# those packages' plugins get loaded too and can break collection outright
# (ROS 2's `launch_testing` does exactly this). Clearing PYTHONPATH makes local
# runs behave identically to CI, where the environment is already clean.
#
# See CONTRIBUTING.md ("A clean PYTHONPATH").

export PYTHONPATH :=

.DEFAULT_GOAL := help

.PHONY: help sync lint format typecheck test test-cov check contract ui ui-check docs docs-reference docs-serve labels-verify ingest verify case-study-check shipped-card vocabulary vocabulary-check lean lean-gate calculus build clean

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

sync:  ## Install all dependency groups
	uv sync --all-groups

lint:  ## Lint and check formatting (no writes)
	uv run ruff check .
	uv run ruff format --check .

format:  ## Auto-fix lint and format in place
	uv run ruff check --fix .
	uv run ruff format .

typecheck:  ## Typecheck src, tests, the case-study tools and the repository tools
	uv run mypy src tests tools case-study/tools

test:  ## Run the test suite with the network blocked
	uv run pytest --block-network

test-cov:  ## Run tests with coverage, enforcing the CI floor
	uv run pytest --block-network --cov --cov-report=term-missing --cov-fail-under=90

check: lint typecheck test-cov  ## Everything CI gates on

# Flags reach the tool through ARGS, not through `--`: `make ingest -- --dry-run`
# would pass `--dry-run` to make as a second *goal*, running the ingest for real
# before complaining that no rule builds `--dry-run`. These targets refuse that
# form up front rather than after the fact.
define refuse_stray_goals
	@extra="$(filter-out $@,$(MAKECMDGOALS))"; \
	if [ -n "$$extra" ]; then \
		echo "make $@: unexpected argument(s): $$extra" >&2; \
		echo 'to pass flags to the tool, use ARGS="..." — e.g. make $@ ARGS="--dry-run"' >&2; \
		exit 2; \
	fi
endef

contract:  ## Regenerate the wire schema and the golden fixture
	# Two generated artifacts, one hand-maintained description: the pydantic models. A
	# test in `make check` fails when either is stale, so this is a convenience rather
	# than the guard.
	uv run python -c "\
from chainlens.ledger.schema import SCHEMA_DIR, render_schemas; \
SCHEMA_DIR.mkdir(parents=True, exist_ok=True); \
[ (SCHEMA_DIR / name).write_text(text, encoding='utf-8') for name, text in render_schemas().items() ]; \
print('wrote', *sorted(p.name for p in SCHEMA_DIR.glob('*.json')))"

	uv run python tests/ledger/fixtures.py
	# The prior goldens, for the one piece of arithmetic the browser does itself. Generated by
	# calling the library's own implementation rather than by re-stating its formula.
	uv run python tests/ui/posterior_cases.py
	# The zod schemas are generated from the JSON Schema, so they follow it. Regenerating them
	# needs Node, and a Python-only contributor should not have to install a JS toolchain to run
	# `make check` -- so a missing node_modules is reported rather than treated as a failure.
	@if [ -d web/node_modules ]; then \
		npm --prefix web run --silent schema; \
	else \
		echo "note: web/node_modules is absent, so the zod schemas were not regenerated"; \
	fi

ui:  ## Build the front-end bundle into the package
	# The output lands in src/chainlens/ui/static/, which is inside the wheel's package root --
	# committing it there is what makes `pip install` work without Node.
	cd web && npm run build

ui-check:  ## Lint, typecheck, test and build the front end, and fail on a stale bundle
	# None of these are optional: `ruff`, `mypy` and `pytest` do not see `web/`, so without them the
	# front end would be the only ungated region in the tree.
	cd web && npm run lint
	cd web && npm test
	cd web && npm run build
	@git diff --exit-code -- src/chainlens/ui/static || { \
		echo "the committed bundle is out of date; run \`make ui\` and commit the result"; \
		exit 1; \
	}

labels-verify:  ## Re-check every label corroboration against the chain
	# Not part of `check`: it needs the network and the suite runs under --block-network. The
	# offline half -- that every record *carries* a dated corroboration -- is a test.
	uv run python tests/labels/verify_corroboration.py

docs-reference:  ## Regenerate the API reference from the docstrings
	# The pages are committed, so the guard is `tests/docs/test_reference.py` -- it runs under
	# `make check` and fails on a diff, which makes this a convenience rather than the check.
	# Same arrangement as `make contract`, for the same reason: one hand-maintained description
	# (the docstrings) and generated artifacts that cannot be allowed to drift from it.
	uv run python tests/docs/gen_reference.py

docs:  ## Build the book (linkcheck runs as a preprocessor, so a broken link fails it)
	# mdbook is not a Python dependency and this target is not part of `check`; the guard that
	# runs everywhere is the staleness test above. This is what a reader builds, and what CI
	# builds to prove the book is buildable.
	mdbook build

docs-serve:  ## Serve the book at localhost:3000, rebuilding on change
	mdbook serve --open

ingest:  ## Digest everything dropped in case-study/inbox (ARGS="--dry-run" to preview)
	# Never part of `check`: it consumes whatever a person put in the inbox.
	$(refuse_stray_goals)
	uv run python case-study/tools/ingest.py $(ARGS)

verify:  ## Re-run every case-study claim record and check the verdicts reproduce
	# Deliberately not part of `check`: it reaches the network, and it needs the
	# corpus, which is gitignored. See case-study/README.md.
	$(refuse_stray_goals)
	uv run python case-study/tools/verify.py $(ARGS)

case-study-check:  ## The case study's static guardrails, no network needed
	uv run pytest tests/case_study -q

shipped-card:  ## Render the package's own presets into the shipped keycard
	# The YAML under `presets/data/` is the hand-edited source; this renders it into
	# `src/chainlens/_shipped_card.py` so that the library's data and a holder's are one object
	# rather than two. The *guard* is `tests/keycard/test_shipped.py`, which fails on a diff and
	# runs in `make check` -- same arrangement as `make vocabulary` and `make contract`.
	uv run python tools/gen_shipped_data.py

vocabulary:  ## Regenerate the vocabulary table's artefacts
	# One hand-written table (`specs/vocabulary/vocabulary.toml`) and four generated files: the
	# asset JSON Schema, the Python rows, the Lean rows, and the Lean gate that carries one
	# `#print axioms` per row. The *guard* is `tests/vocabulary/test_the_table.py`, which fails
	# on a diff and runs in `make check` -- same arrangement as `make contract` and
	# `make docs-reference`, and for the same reason.
	uv run python tools/gen_vocabulary.py

vocabulary-check:  ## Report whether the table and its artefacts agree, writing nothing
	uv run python tools/gen_vocabulary.py --check

lean:  ## Build the Lean development of the calculus
	# Not part of `check`: a Lean toolchain is not a Python dependency, and this is the one
	# target in the file that needs a tool that `uv sync` will not install. The guard that
	# does run everywhere is `tests/calculus/test_lean_claims.py`, and it reads the gate
	# files and the sources rather than building anything.
	#
	# One module needs Mathlib, so a first run needs its olean cache -- a minute, not the
	# hours a from-source build takes:
	#     cd lean && lake exe cache get
	cd lean && lake build

lean-gate:  ## Refuse a proof in the calculus that rests on an axiom we did not agree to
	# The tool builds first, and that is not a convenience: `lake env lean` resolves an
	# `import` to the compiled olean rather than to the source, so a `sorry` added and not
	# rebuilt is invisible to the gate, which then reports a clean result for a proof with a
	# hole in it. See the tool's docstring, where that was measured rather than reasoned about.
	uv run python tools/check_lean_axioms.py

calculus:  ## The whole calculus: the build, the gate, the vocabulary, the correspondence
	$(MAKE) lean
	$(MAKE) vocabulary-check
	uv run python tools/gen_shipped_data.py --check
	$(MAKE) lean-gate
	uv run pytest tests/calculus tests/vocabulary -q

build:  ## Build wheel and sdist
	uv build

clean:  ## Remove build and tool caches
	rm -rf build dist site .pytest_cache .mypy_cache .ruff_cache .hypothesis htmlcov
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
