# chainlens development tasks.
#
# PYTHONPATH is deliberately emptied for every target.
#
# Rationale: a contributor's shell may have unrelated site-packages on
# PYTHONPATH — e.g. a sourced ROS 2 workspace, a conda env, another project's
# install tree. pytest auto-loads every `pytest11` entry point it can see, so
# those packages' plugins get loaded too and can break collection outright
# (ROS 2's `launch_testing` does exactly this). Clearing PYTHONPATH makes local
# runs behave identically to CI, where the environment is already clean.
#
# See CONTRIBUTING.md ("A clean PYTHONPATH").

export PYTHONPATH :=

.DEFAULT_GOAL := help

.PHONY: help sync lint format typecheck test test-cov check contract ui ui-check ingest verify case-study-check build clean

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

sync:  ## Install all dependency groups
	uv sync --all-groups

lint:  ## Lint and check formatting (no writes)
	uv run ruff check .
	uv run ruff format --check .

format:  ## Auto-fix lint and format in place
	uv run ruff check --fix .
	uv run ruff format .

typecheck:  ## Typecheck src, tests, and the case-study tools
	uv run mypy src tests case-study/tools

test:  ## Run the test suite with the network blocked
	uv run pytest --block-network

test-cov:  ## Run tests with coverage, enforcing the CI floor
	uv run pytest --block-network --cov --cov-report=term-missing --cov-fail-under=90

check: lint typecheck test-cov  ## Everything CI gates on

# Flags reach the tool through ARGS, not through `--`: `make ingest -- --dry-run`
# would pass `--dry-run` to make as a second *goal*, running the ingest for real
# before complaining that no rule builds `--dry-run`. These targets refuse that
# form up front rather than after the fact.
define refuse_stray_goals
	@extra="$(filter-out $@,$(MAKECMDGOALS))"; \
	if [ -n "$$extra" ]; then \
		echo "make $@: unexpected argument(s): $$extra" >&2; \
		echo 'to pass flags to the tool, use ARGS="..." — e.g. make $@ ARGS="--dry-run"' >&2; \
		exit 2; \
	fi
endef

contract:  ## Regenerate the wire schema and the golden fixture
	# Two generated artifacts, one hand-maintained description: the pydantic models. A
	# test in `make check` fails when either is stale, so this is a convenience rather
	# than the guard.
	uv run python -c "\
from chainlens.ledger.schema import SCHEMA_DIR, render_schemas; \
SCHEMA_DIR.mkdir(parents=True, exist_ok=True); \
[ (SCHEMA_DIR / name).write_text(text, encoding='utf-8') for name, text in render_schemas().items() ]; \
print('wrote', *sorted(p.name for p in SCHEMA_DIR.glob('*.json')))"

	uv run python tests/ledger/fixtures.py
	# The prior goldens, for the one piece of arithmetic the browser does itself. Generated by
	# calling the library's own implementation rather than by re-stating its formula.
	uv run python tests/ui/posterior_cases.py
	# The zod schemas are generated from the JSON Schema, so they follow it. Regenerating them
	# needs Node, and a Python-only contributor should not have to install a JS toolchain to run
	# `make check` -- so a missing node_modules is reported rather than treated as a failure.
	@if [ -d web/node_modules ]; then \
		npm --prefix web run --silent schema; \
	else \
		echo "note: web/node_modules is absent, so the zod schemas were not regenerated"; \
	fi

ui:  ## Build the front-end bundle into the package
	# The output lands in src/chainlens/ui/static/, which is inside the wheel's package root --
	# committing it there is what makes `pip install` work without Node.
	cd web && npm run build

ui-check:  ## Typecheck, test and build the front end, and fail on a stale bundle
	# The test run is not optional here: `ruff`, `mypy` and `pytest` do not see `web/`, so without
	# it the front end would be the only ungated region in the tree.
	cd web && npm test
	cd web && npm run build
	@git diff --exit-code -- src/chainlens/ui/static || { \
		echo "the committed bundle is out of date; run \`make ui\` and commit the result"; \
		exit 1; \
	}

ingest:  ## Digest everything dropped in case-study/inbox (ARGS="--dry-run" to preview)
	# Never part of `check`: it consumes whatever a person put in the inbox.
	$(refuse_stray_goals)
	uv run python case-study/tools/ingest.py $(ARGS)

verify:  ## Re-run every case-study claim record and check the verdicts reproduce
	# Deliberately not part of `check`: it reaches the network, and it needs the
	# corpus, which is gitignored. See case-study/README.md.
	$(refuse_stray_goals)
	uv run python case-study/tools/verify.py $(ARGS)

case-study-check:  ## The case study's static guardrails, no network needed
	uv run pytest tests/case_study -q

build:  ## Build wheel and sdist
	uv build

clean:  ## Remove build and tool caches
	rm -rf build dist site .pytest_cache .mypy_cache .ruff_cache .hypothesis htmlcov
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
