"""GENERATED FILE - DO NOT EDIT BY HAND.

Generated by `tools/gen_shipped_data.py` from `src/chainlens/presets/data/*.yaml`.

The shipped presets, in the card, so that the library's data and a holder's data are one object
rather than two that must be looked in separately. **The YAML under `presets/data/` is the
hand-edited source**; edit that and run `make shipped-card`.

Only presets are rendered, and the asymmetry with labels is deliberate: a card entry for a preset
is the same `Preset` the YAML produces, so nothing is lost, where a shipped *label* carries a
corroboration a card entry has no way to hold.

Edit the YAML and run `make shipped-card`. `tests/keycard/test_shipped.py` fails when this file is
stale, so it cannot drift from its source silently.
"""

from __future__ import annotations

from typing import Final

from chainlens.models.enums import Chain
from chainlens.presets.records import Preset, RateTier

__all__ = ["SHIPPED_PRESETS"]


SHIPPED_PRESETS: Final[tuple[Preset, ...]] = (
    Preset(
        name='ethereum-ico',
        description="The ether pre-sale of July-September 2014. Bitcoin was paid in to one address, and the ether was issued in the genesis block in proportion to what each participant paid — so there is no transfer between a row's two addresses to find, and a check that looked for one would report a miss on every row.",
        chain=Chain('ethereum'),
        source='https://github.com/ethereum/go-ethereum/wiki/Launching-the-Ether-Sales',
        funding_address='36PrZ1KHYMpqSyAQXSG8VwbUiq2EogxLo2',
        rates=(
            RateTier(rate=2000.0, note='the opening rate, the first fourteen days'),
            RateTier(rate=1750.0, note='the second two weeks'),
            RateTier(rate=1500.0, note='the third two weeks'),
            RateTier(rate=1337.0, note='the final period, at the rate the sale closed on'),
        ),
        allocation_dataset="The genesis allocation: 8,893 prefund allocations, published in go-ethereum's alloc file and mirrored by Nethermind at https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Chains/foundation.json",
        notes=("The ether was minted at genesis rather than transferred, so a row's two addresses are a *common-control* assertion and not a payment. No transaction can confirm or refute it.", "A row's implied rate is a blend when it reports totals or a purchase that straddled a rate change, so a row matching no tier is a question rather than an error."),
    ),
)
