"""The prior transform, pinned as data for the browser.

The prior is a **view parameter that never leaves the browser**. It has to be: the library
ships no default prior and emits no posterior, and round-tripping every drag of a slider to
a local server would be both laggy and impossible in the static mode the app is designed to
run in. So the one piece of arithmetic the app performs itself is ``odds = exp(logit(prior)
+ log10_lr·ln 10)``, and this module is what stops that copy from drifting.

Every case here is generated by calling the reference implementation —
:meth:`LikelihoodRatio.posterior_probability` — on a ratio built by the real
:func:`evaluate_likelihood`, so the expected values are the library's own answers rather than
a re-derivation of its formula. If the formula changes, the file regenerates and the
TypeScript assertion fails; that is the whole mechanism.

Three things are emitted, and each exists because of a way the browser copy could be wrong:

* **the cases** — ``(prior, log10_lr, expected)`` rows across the range the app can produce,
  asserted in TypeScript at 1e-12;
* **the rejected priors** — the values :meth:`posterior_probability` refuses, *verified* to
  raise here rather than merely listed, so the TypeScript refusal is parity with the library
  rather than a second opinion about what a prior may be;
* **the unbounded case** — a ratio that came out infinite, which the wire writes as an absent
  logarithm plus ``lr_at_least``. A posterior cannot be computed from it, and the browser has
  to refuse rather than invent a finite logarithm. ``inf`` never appears in this file, because
  it is not JSON: the same rule the wire contract enforces everywhere else.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from chainlens.verify import (
    ComponentEstimate,
    EstimatorMethod,
    LikelihoodRatio,
    NullModel,
    evaluate_likelihood,
    wilson_interval,
)

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "posterior_cases.json"

#: The implementation this file's expected values came from, written into the fixture so the
#: TypeScript copy cannot quietly become the only description of the arithmetic.
REFERENCE = "chainlens.verify.likelihood.LikelihoodRatio.posterior_probability"

#: A component with `successes` coincidences out of `trials`, with its Wilson interval. The
#: population string is the kind a real estimator would carry, so nothing here is a shape the
#: library cannot actually produce.
_TRIALS = 100_000

#: `(k, successes)` pairs. Each is priced by the real engine, so the resulting `log10_lr` values
#: are whatever the library computes rather than values chosen to make a table look tidy — the
#: spread they happen to give is the spread the app will actually see. `(1, 100_000)` is the
#: degenerate end where a coincidence is certain and the ratio is exactly 1.
_PRICED = (
    # The degenerate end: one opportunity and a coincidence that is certain, so the ratio is
    # exactly 1 and the posterior is the prior. The transform must not move it.
    (1, 100_000),
    # And the strong end: 100,000:1 on a single opportunity, which is where a prior near 1 and a
    # posterior near 1 both turn up — the region where an implementation that used odds where it
    # meant log-odds would still look plausible.
    (1, 1),
    (1, 1_000),
    (2, 100),
    (5, 10),
    (10, 10),
    (10, 1),
    (100, 10),
    (412, 10),
    (1_000, 10),
    (5_000, 10),
)

#: Priors the app's slider can reach, including both ends of the scale and a coin flip.
_PRIORS = (1e-6, 1e-4, 0.001, 0.01, 0.1, 0.25, 0.5, 0.9, 0.999, 0.999_999)

#: Values `posterior_probability` refuses. A prior of exactly 0 or 1 cannot be moved by any
#: evidence, which is almost always a mistake rather than a belief.
_REJECTED = (0.0, 1.0, -0.001, 1.001, -1.0, 2.0)


def _component(successes: int, trials: int = _TRIALS) -> ComponentEstimate:
    """A coincidence estimate with the interval its counts imply."""
    lower, upper = wilson_interval(successes, trials)
    return ComponentEstimate(
        value=successes / trials,
        successes=successes,
        trials=trials,
        ci_lower=lower,
        ci_upper=upper,
        method=EstimatorMethod.EMPIRICAL_JOINT,
        population=f"{trials} transfers in the window, sender cluster excluded",
    )


def _ratio(k: int, successes: int) -> LikelihoodRatio:
    """A real ratio from the real engine, swept rather than assembled by hand."""
    return evaluate_likelihood(
        k=k,
        component=_component(successes),
        null_model=NullModel.WITHIN_SENDER,
    )


def _finite_cases() -> list[dict[str, Any]]:
    cases: list[dict[str, Any]] = []
    for k, successes in _PRICED:
        ratio = _ratio(k, successes)
        log10_lr = ratio.log10_lr
        if log10_lr is None or not math.isfinite(log10_lr):
            raise AssertionError(
                f"k={k} with {successes} successes did not price to a finite logarithm"
            )
        cases.extend(
            {
                "k": k,
                "successes": successes,
                # Recorded so a reader of the file can see what evidence the row is about, not
                # because the transform reads it.
                "lr": ratio.lr,
                "log10_lr": log10_lr,
                "prior": prior,
                "expected": ratio.posterior_probability(prior),
            }
            for prior in _PRIORS
        )
    return cases


def _rejected_priors() -> list[dict[str, Any]]:
    """The priors the library refuses, each verified to raise rather than assumed to.

    Non-finite priors are checked too, but they are not *listed* as numbers: JSON cannot carry
    an infinity or a NaN, and writing one as `null` would be a different thing from the value
    the library rejects.
    """
    ratio = _ratio(5, 10)
    rejected: list[dict[str, Any]] = []
    for prior in _REJECTED:
        try:
            ratio.posterior_probability(prior)
        except ValueError as exc:
            rejected.append({"prior": prior, "reason": str(exc)})
        else:  # pragma: no cover - a guard against the library loosening
            raise AssertionError(f"{prior} was accepted as a prior")
    for value in (math.inf, -math.inf, math.nan):
        try:
            ratio.posterior_probability(value)
        except ValueError:
            pass
        else:  # pragma: no cover - a guard against the library loosening
            raise AssertionError(f"{value} was accepted as a prior")
    return rejected


def render_all() -> str:
    """The whole fixture, as strict JSON."""
    unbounded = _ratio(5, 0)
    # The domain model keeps an infinite ratio — it is mathematically correct — and the *wire*
    # model is what turns it into an absent logarithm plus `lr_at_least`. Checked through
    # `isfinite` rather than against a literal `inf`, because that is the predicate the wire
    # model uses and the one the browser will have to use.
    if unbounded.log10_lr is not None and math.isfinite(unbounded.log10_lr):
        raise AssertionError("a zero coincidence probability no longer prices to an infinite ratio")

    return (
        json.dumps(
            {
                "schema_version": 1,
                "reference": REFERENCE,
                "note": (
                    "Every `expected` was produced by the reference implementation above, on a "
                    "ratio assembled by `evaluate_likelihood`. The TypeScript transform is a copy "
                    "of the arithmetic that the library performs, made because the prior never "
                    "leaves the browser."
                ),
                "cases": _finite_cases(),
                "rejected_priors": _rejected_priors(),
                "unbounded": {
                    "k": 5,
                    "successes": 0,
                    "lr_is_infinite": not math.isfinite(unbounded.lr),
                    "log10_lr": None,
                    "note": (
                        "A zero coincidence probability gives an infinite ratio, which the wire "
                        "writes as an absent logarithm plus `lr_at_least`. A posterior cannot be "
                        "computed from it, and the app refuses rather than inventing a finite "
                        "logarithm. `inf` is not in this file because it is not JSON."
                    ),
                },
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


if __name__ == "__main__":  # pragma: no cover - a regeneration helper, not a code path
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(render_all(), encoding="utf-8")
    print(f"wrote {FIXTURE_PATH}")
