-- GENERATED FILE - DO NOT EDIT BY HAND.
--
-- Generated by `tools/gen_vocabulary.py` from `specs/vocabulary/vocabulary.toml`.
--
-- One `#print axioms` per vocabulary theorem, so the gate covers every row rather than
-- the ones somebody remembered. Run by `tools/check_lean_axioms.py`, which refuses any
-- axiom set outside `propext`, `Classical.choice` and `Quot.sound`.
--
-- **The generator and the table arrive in tranche T1.** Until then this file is
-- hand-written and holds the one theorem the hand-written vocabulary supports, which is
-- deliberate rather than a placeholder: it is what makes the gate cover *two* files, so
-- that the tool which refuses a gap is itself exercised before it is relied on.

import Chainlens.Dim

-- The vocabulary has as many rows as it says it has. A theorem rather than a remark:
-- widening the table without widening this breaks the gate rather than a downstream
-- arithmetic that silently reads a row that is not there.
#print axioms Chainlens.Dim.rows_length
