-- GENERATED FILE - DO NOT EDIT BY HAND.
--
-- Generated by `tools/gen_vocabulary.py` from `specs/vocabulary/vocabulary.toml`.
--
-- One `#print axioms` per vocabulary theorem, so the gate covers every row rather than the
-- ones somebody remembered. Run by `tools/check_lean_axioms.py`, which refuses any axiom set
-- outside `propext`, `Classical.choice` and `Quot.sound`.
--
-- **Why this file is generated and `Axioms.lean` is not.** `Axioms.lean` holds the general
-- theorems, beside the prose explaining what the gate is for, and a person writes those. This
-- holds one line per row of the table, and a hand-maintained list of every asset goes stale the
-- first time one is added — silently, because the theorem stays proved and nothing gates it.
--
-- Edit the table and run `make vocabulary`.

import Chainlens.Vocabulary

#print axioms Chainlens.Vocabulary.assets_length
#print axioms Chainlens.Vocabulary.btc_is_row_0
#print axioms Chainlens.Vocabulary.btc_basis
#print axioms Chainlens.Vocabulary.tbtc_is_row_1
#print axioms Chainlens.Vocabulary.tbtc_basis
#print axioms Chainlens.Vocabulary.ltc_is_row_2
#print axioms Chainlens.Vocabulary.ltc_basis
#print axioms Chainlens.Vocabulary.doge_is_row_3
#print axioms Chainlens.Vocabulary.doge_basis
#print axioms Chainlens.Vocabulary.bch_is_row_4
#print axioms Chainlens.Vocabulary.bch_basis
#print axioms Chainlens.Vocabulary.eth_is_row_5
#print axioms Chainlens.Vocabulary.eth_basis
