-- GENERATED FILE - DO NOT EDIT BY HAND.
--
-- Generated by `tools/gen_vocabulary.py` from `specs/vocabulary/vocabulary.toml`.
--
-- The vocabulary, as the free abelian group's basis. One theorem per row, so that widening
-- the table without widening the proofs breaks the build rather than a downstream arithmetic,
-- and so that a row whose exponent vector is not the unit vector at its own position fails to
-- compile instead of being read as a different asset.
--
-- Edit the table and run `make vocabulary`. `tests/vocabulary/test_the_table.py` fails when
-- this file is stale.
--
-- Where this disagrees with `docs/calculus/vocabulary.md`, the page is right and this is a
-- bug.

import Chainlens.Dim

namespace Chainlens.Vocabulary

open Chainlens.Dim

/-- The vocabulary, in the table's order. **That order is the basis order**: a dimension is a
weight per row *by position*, so reordering this list permutes every exponent vector at once. -/
def assets : List Row := [
  ("bitcoin", "btc"),
  ("bitcoin_testnet", "tbtc"),
  ("litecoin", "ltc"),
  ("dogecoin", "doge"),
  ("bitcoin_cash", "bch"),
  ("ethereum", "eth")
]

/-- The table has as many rows as it says it has. A theorem rather than a remark, because a
wider table with a stale count is a basis with a phantom member. -/
theorem assets_length : assets.length = 6 := rfl

/-- Row 0 of the table is `btc`, on `bitcoin`.

The generator writes both this theorem and the row it is about, so what it rules out is a table
edited in one place and not the other: a row inserted above this one shifts it and the theorem
stops elaborating. The table says of it: The native coin of Bitcoin, and the only asset this library can price from a post. -/
theorem btc_is_row_0 : assets[0]? = some ("bitcoin", "btc") :=
  rfl

/-- `btc`'s exponent vector weights its own row by one and every other row by zero.

The two halves of the layer's freedom claim, for this row: `weight_unit_self` says the row is
weighted at all, and `weight_unit_other` says the rows are independent of one another. Stated
per row rather than once, so that adding a row without adding its proof is a build failure. -/
theorem btc_basis (j : Nat) :
    weight (unit 6 0) j = if j = 0 then 1 else 0 := by
  by_cases h : j = 0
  · rw [if_pos h, h, weight_unit_self 6 0 (by decide)]
  · rw [if_neg h, weight_unit_other 6 0 j h]

/-- Row 1 of the table is `tbtc`, on `bitcoin_testnet`.

The generator writes both this theorem and the row it is about, so what it rules out is a table
edited in one place and not the other: a row inserted above this one shifts it and the theorem
stops elaborating. The table says of it: Testnet bitcoin, which shares the mainnet ticker: the symbol is a display convention and the chain is what tells them apart, so `(chain, asset)` is the identity and not `symbol`. -/
theorem tbtc_is_row_1 : assets[1]? = some ("bitcoin_testnet", "tbtc") :=
  rfl

/-- `tbtc`'s exponent vector weights its own row by one and every other row by zero.

The two halves of the layer's freedom claim, for this row: `weight_unit_self` says the row is
weighted at all, and `weight_unit_other` says the rows are independent of one another. Stated
per row rather than once, so that adding a row without adding its proof is a build failure. -/
theorem tbtc_basis (j : Nat) :
    weight (unit 6 1) j = if j = 1 then 1 else 0 := by
  by_cases h : j = 1
  · rw [if_pos h, h, weight_unit_self 6 1 (by decide)]
  · rw [if_neg h, weight_unit_other 6 1 j h]

/-- Row 2 of the table is `ltc`, on `litecoin`.

The generator writes both this theorem and the row it is about, so what it rules out is a table
edited in one place and not the other: a row inserted above this one shifts it and the theorem
stops elaborating. The table says of it: No provider in this tree serves Litecoin yet; the row exists so its decimals are not written down elsewhere. -/
theorem ltc_is_row_2 : assets[2]? = some ("litecoin", "ltc") :=
  rfl

/-- `ltc`'s exponent vector weights its own row by one and every other row by zero.

The two halves of the layer's freedom claim, for this row: `weight_unit_self` says the row is
weighted at all, and `weight_unit_other` says the rows are independent of one another. Stated
per row rather than once, so that adding a row without adding its proof is a build failure. -/
theorem ltc_basis (j : Nat) :
    weight (unit 6 2) j = if j = 2 then 1 else 0 := by
  by_cases h : j = 2
  · rw [if_pos h, h, weight_unit_self 6 2 (by decide)]
  · rw [if_neg h, weight_unit_other 6 2 j h]

/-- Row 3 of the table is `doge`, on `dogecoin`.

The generator writes both this theorem and the row it is about, so what it rules out is a table
edited in one place and not the other: a row inserted above this one shifts it and the theorem
stops elaborating. The table says of it: No provider in this tree serves Dogecoin yet. Dogecoin has no bech32 address form. -/
theorem doge_is_row_3 : assets[3]? = some ("dogecoin", "doge") :=
  rfl

/-- `doge`'s exponent vector weights its own row by one and every other row by zero.

The two halves of the layer's freedom claim, for this row: `weight_unit_self` says the row is
weighted at all, and `weight_unit_other` says the rows are independent of one another. Stated
per row rather than once, so that adding a row without adding its proof is a build failure. -/
theorem doge_basis (j : Nat) :
    weight (unit 6 3) j = if j = 3 then 1 else 0 := by
  by_cases h : j = 3
  · rw [if_pos h, h, weight_unit_self 6 3 (by decide)]
  · rw [if_neg h, weight_unit_other 6 3 j h]

/-- Row 4 of the table is `bch`, on `bitcoin_cash`.

The generator writes both this theorem and the row it is about, so what it rules out is a table
edited in one place and not the other: a row inserted above this one shifts it and the theorem
stops elaborating. The table says of it: No provider in this tree serves Bitcoin Cash yet. Its cashaddr form is deliberately not listed: `families` names what this library can validate, and nothing here implements it. -/
theorem bch_is_row_4 : assets[4]? = some ("bitcoin_cash", "bch") :=
  rfl

/-- `bch`'s exponent vector weights its own row by one and every other row by zero.

The two halves of the layer's freedom claim, for this row: `weight_unit_self` says the row is
weighted at all, and `weight_unit_other` says the rows are independent of one another. Stated
per row rather than once, so that adding a row without adding its proof is a build failure. -/
theorem bch_basis (j : Nat) :
    weight (unit 6 4) j = if j = 4 then 1 else 0 := by
  by_cases h : j = 4
  · rw [if_pos h, h, weight_unit_self 6 4 (by decide)]
  · rw [if_neg h, weight_unit_other 6 4 j h]

/-- Row 5 of the table is `eth`, on `ethereum`.

The generator writes both this theorem and the row it is about, so what it rules out is a table
edited in one place and not the other: a row inserted above this one shifts it and the theorem
stops elaborating. The table says of it: The native coin of Ethereum. `families` is EIP-55 alone because a lowercase `0x` address carries no checksum to check; `codec/eth_address.py` accepts one and the notes identifier layer is where the absence of a checksum is recorded as a caveat rather than a failure. -/
theorem eth_is_row_5 : assets[5]? = some ("ethereum", "eth") :=
  rfl

/-- `eth`'s exponent vector weights its own row by one and every other row by zero.

The two halves of the layer's freedom claim, for this row: `weight_unit_self` says the row is
weighted at all, and `weight_unit_other` says the rows are independent of one another. Stated
per row rather than once, so that adding a row without adding its proof is a build failure. -/
theorem eth_basis (j : Nat) :
    weight (unit 6 5) j = if j = 5 then 1 else 0 := by
  by_cases h : j = 5
  · rw [if_pos h, h, weight_unit_self 6 5 (by decide)]
  · rw [if_neg h, weight_unit_other 6 5 j h]

end Chainlens.Vocabulary
