// GENERATED FROM schema/derivation.schema.json -- DO NOT EDIT.
// Regenerate with `make contract`. A CI job regenerates and fails on a diff.

import { z } from "zod";

export const BindingSchema = z.enum(["bound","unbound"]).describe("Whether an input has a value at all.")

export const BoundDirectionSchema = z.enum(["point","lower","upper"]).describe("How much of a value a bound gives.\n\n``POINT`` is the value itself. ``LOWER`` and ``UPPER`` are one-sided: the true number is at or\nabove (or at or below) this one, and which way the error runs is stated rather than implied.\n\nThis is deliberately *not* fused into :class:`Binding`. \"Is there a value\" and \"how good is it\"\nare different questions, and a truncated scan answers the first with yes and the second with\n``LOWER`` — which a single enum could only express by inventing a member per combination.")

export const ClaimVerdictSchema = z.enum(["supported","contradicted","unresolved"]).describe("The categorical finding about a claim.\n\nDeliberately about the *match structure* rather than about probability. The\nlikelihood ratio is a separate quantity attached alongside; deriving a verdict\nfrom it would conflate \"what the chain shows\" with \"how much that is worth\",\nwhich the verification layer keeps strictly apart.\n\nThree members, and the third is not a finding about the claim at all: it says nothing was\ndecided, and *why* is carried on the finding's\n:attr:`~chainlens.verify.verdicts.VerificationFinding.gap` — an input with no value, which\nknows whether nothing here could obtain it (``no_method``), whether something could and the\ndata was not reachable (``no_data``), or whether nobody asked (``not_requested``).\n\nThe two were separate members once, ``UNVERIFIABLE`` and ``INSUFFICIENT_DATA``, on the\nargument that they mean opposite things to a reader — stop asking versus configure\nsomething. That argument was right and it is why the kinds exist; what was wrong was\nspelling it twice. A verdict is either decided or it is not, and the reason it is not is a\nproperty of an input rather than a fourth way for a claim to come out.")

export const DerivationKindSchema = z.enum(["claim","verdict","proposition","evidence","quantity_k","quantity_p","likelihood_ratio","sensitivity","verbal_band","posterior","assumption","caveat","because"]).describe("What one node of the derivation is.\n\nThe kinds are the *vocabulary of the argument*, not of the data: ``QUANTITY_K`` and\n``QUANTITY_P`` are separate from ``EVIDENCE`` because a measured number and the finding\nthat produced it are different claims, and ``BECAUSE`` exists so the refusal case has a\nnode of its own rather than being smuggled into a verdict's label.")

export const VerbalScaleSchema = z.enum(["none","slight","moderate","moderately strong","strong","very strong"]).describe("Belief in a proposition, on the ENFSI verbal scale.\n\nTaken from the appendix of the *ENFSI Guideline for Evaluative Reporting in\nForensic Science* (2015). The guideline treats the verbal scale as optional\nand jurisdiction-dependent and prefers the numeric ratio where one can be\ngiven, so the boundaries behind these bands are configurable -- see\n:class:`~chainlens.verify.scale.VerbalThresholds` -- and these labels are the\ndefault rather than a universal standard.")

export const DetailKindSchema = z.enum(["string","int","float","bool","list","null"]).describe("The six scalars a detail value can be.\n\nSix, not \"any\": a value that is none of these is refused rather than stringified,\nbecause stringifying is how a nested object becomes text that reads like a finding.\n\n``INT`` carries its value as a **decimal string**, for the reason\n:data:`BaseUnits` sets out: a detail may be an amount, and an amount in a browser is a\ndouble. A detail is free-form, so there is no field type to hang the rule on and it\nbelongs to the kind instead.")

export const DetailEntrySchema = z.object({ "key": z.string(), "kind": DetailKindSchema, "unit": z.union([z.string(), z.null()]).default(null), "value": z.union([z.string(), z.number().int(), z.number(), z.boolean(), z.array(z.string()), z.null()]).default(null) }).strict().describe("One labelled fact, in a form two languages can render identically.\n\nAttributes:\n    key: the checker's own key, unchanged.\n    kind: which scalar this is, so a renderer needs no narrowing.\n    value: the value, or ``None`` when ``kind`` is ``null``.\n    unit: an optional unit for a number, e.g. ``\"base units\"``.")

export const GraphRefKindSchema = z.enum(["node","edge"]).describe("What a reference points at. An edge is addressable here, unlike in the flow view.")

export const GraphRefSchema = z.object({ "exists": z.union([z.boolean(), z.null()]).default(null), "key": z.string(), "kind": GraphRefKindSchema, "note": z.union([z.string(), z.null()]).default(null) }).strict().describe("A pointer into a ledger document, which may or may not hold it.\n\nAttributes:\n    kind: whether the reference names a node or an edge.\n    key: the node or edge key. Node keys are ``address:``/``tx:``/``unparsed:``;\n        edge keys are ``{txid}:in|out|tok|int:{index}``.\n    exists: whether it was found in the document it was resolved against. ``None``\n        means nobody has looked — which is not the same as absent, and a front end\n        should offer to fetch rather than reporting nothing there.\n    note: why it was not found, when something knows.")

export const UnboundKindSchema = z.enum(["no_method","no_data","not_requested"]).describe("Why an input has no value.\n\nThese are the three answers, and they are not interchangeable: the first says stop\nasking, the second says configure something or wait for data, and the third says nobody\nasked. A reader who cannot tell them apart cannot tell a gap in their own setup from a\nlimit of the chain.")

export const SourceKindSchema = z.enum(["observed","counted","estimated","convention","supplied","assumed"]).describe("What kind of thing put a value where it is.\n\nA reader deciding how much to trust a number needs to know whether it was read off the chain,\ntallied from reads, priced from a sample, chosen by convention, or handed in by somebody — and\n\"chosen by convention\" is the kind most easily mistaken for a measurement, which is why it is a\nkind rather than a footnote.")

export const SourceSchema = z.object({ "kind": SourceKindSchema, "text": z.string() }).strict().describe("Where a bound value came from.\n\n``text`` is the sentence a reader needs — \"the sender's movements in the window\", \"the hedge\nword '~' licenses a 5% band\" — and ``kind`` is the part a machine can act on, so that a\nconvention can be told from a measurement without reading prose.")

export const InputSchema = z.object({ "binding": BindingSchema, "detail": z.array(DetailEntrySchema).default([]), "direction": BoundDirectionSchema, "kind": z.union([UnboundKindSchema, z.null()]).default(null), "label": z.string(), "name": z.string(), "reason": z.union([z.string(), z.null()]).default(null), "source": z.union([SourceSchema, z.null()]).default(null), "unit": z.union([z.string(), z.null()]).default(null), "value": z.union([z.number(), z.null()]).default(null) }).strict().describe("One value a calculation rests on, and everything about where it stands.\n\nThe two halves are disjoint and a validator enforces it: bound inputs carry a value and a\nsource, unbound ones carry a kind and a reason. That is the structural guarantee replacing the\nprose vocabularies — there is no construction in which an input both has a value and does not.\n\nAttributes:\n    name: the stable slot this input fills — ``k``, ``p``, ``band``, ``prior``. What\n        :attr:`Operation.inputs` refers to.\n    label: what to show a reader. Written here rather than in a renderer, for the reason\n        :class:`~chainlens.models.derive.DerivationNode` gives: a label a renderer invents is a\n        claim the library did not make.\n    value: the number, when bound. A count is stored here as well as in ``detail`` — see the\n        note below.\n    unit: what the value is counted in.\n    direction: whether the value is the number or a one-sided bound on it.\n    source: where a bound value came from.\n    kind: why an unbound one has none.\n    reason: the sentence explaining an unbound one, in the words of whoever refused.\n    detail: anything else a reader needs, in the tagged form a second language can render.\n\nA note on precision: ``value`` is a float, matching :class:`DerivationNode`, and exact integers\ntravel in ``detail`` as :class:`~chainlens.models.wire.DetailEntry` — which serialises an int\nas a string for the reason its own docstring gives. Base-unit amounts need that; the counts here\n(bounded by the scan limit) do not, so they are not given a third convention of their own.")

export const OperationKindSchema = z.enum(["coincidence","likelihood_ratio","posterior"]).describe("Which arithmetic was done. One member per formula the library has.")

export const OperationSchema = z.object({ "direction": BoundDirectionSchema, "formula": z.string(), "inputs": z.array(z.string()), "kind": OperationKindSchema, "reason": z.union([z.string(), z.null()]).default(null), "result": z.union([z.number(), z.null()]).default(null) }).strict().describe("One arithmetic step, with the formula it is.\n\nThe formula is not written here. It comes from\n:func:`chainlens.verify.likelihood.formula_for`, which sits beside the functions that compute\nthe numbers, so the displayed formula and the computed value have one home rather than two. A\ntest evaluates the formula string against the function over a grid, which is what catches an\nedit to one that missed the other.\n\nAttributes:\n    kind: which operation this is.\n    formula: the canonical expression, for a reader and for that test.\n    inputs: the **names** of the inputs it consumes, in argument order. Names rather than node\n        ids, because an :class:`RatioAttempt` carries these on a finding, where there is no tree\n        to point into.\n    result: the number, when every input is bound exactly and the answer is defined.\n    direction: whether :attr:`result` is the answer or a one-sided bound on it. An infinite\n        ratio is the case that needs this: the top of the scale is a floor, not the value.\n    reason: why there is no number, when there is none.")

export const DerivationNodeSchema: z.ZodType = z.lazy(() => z.object({ "band": z.union([VerbalScaleSchema, z.null()]).default(null), "children": z.array(DerivationNodeSchema).default([]), "detail": z.array(DetailEntrySchema).default([]), "graph_refs": z.array(GraphRefSchema).default([]), "id": z.string(), "input": z.union([InputSchema, z.null()]).default(null), "kind": DerivationKindSchema, "label": z.string(), "operation": z.union([OperationSchema, z.null()]).default(null), "summary": z.union([z.string(), z.null()]).default(null), "unit": z.union([z.string(), z.null()]).default(null), "value": z.union([z.number(), z.null()]).default(null) }).strict().describe("One step of a derivation, and everything a reader needs to disagree with it.\n\nAttributes:\n    id: a path-derived identifier, stable across runs — ``claim``,\n        ``claim/evidence/0`` — so a renderer can key nodes and a fixture can be\n        compared.\n    kind: what this step is.\n    label: the short thing to show on the node. Written here rather than in the\n        renderer, because a label the renderer invents is a claim the library did not\n        make.\n    summary: a sentence, when the label is not enough.\n    detail: labelled facts, in the tagged form a second language can render.\n    value: the number this step is about, when it is about one.\n    unit: what that number is counted in.\n    band: the verbal band, on the band and posterior nodes.\n    graph_refs: the ledger nodes and edges this step rests on. Carried whether or not\n        they resolve — see :class:`~chainlens.models.wire.GraphRef`.\n    input: what this node *is*, when it is one of the values a calculation rests on. A\n        quantity node carries one; every other node carries neither this nor ``operation``.\n    operation: the arithmetic, when this node is a number that was computed. Present whether or\n        not it produced a result — an operation whose inputs are one-sided or unbound travels\n        with its formula and no value, which is what makes a withheld number read as a hole in a\n        visible calculation rather than as a refusal.\n    children: the steps below this one."));

export const DerivationDocumentSchema = z.object({ "claim_id": z.string(), "claim_quote": z.string(), "has_ratio": z.boolean().default(false), "limitations": z.string(), "method": z.string(), "prior_supplied_by": z.union([z.string(), z.null()]).default(null), "root": DerivationNodeSchema, "schema_version": z.number().int().default(1), "verdict": ClaimVerdictSchema }).strict().describe("One finding's derivation, as a document a front end can render.\n\nAttributes:\n    schema_version: the contract version. Both ends refuse an unknown major.\n    claim_id: derived from the claim, so a graph overlay can group findings by claim.\n    claim_quote: the verbatim span the claim was read from, so a reader can see what is\n        being adjudicated without the graph.\n    verdict: the categorical finding, repeated at the root because it is the thing the\n        tree explains.\n    method: which checker produced the verdict.\n    has_ratio: whether a likelihood ratio was reported. The tree's shape differs, and a\n        renderer should not have to walk it to find out.\n    root: the tree.\n    limitations: the standing caveats. **Replaced when a prior was supplied**, because\n        the standard text says the library reports no posterior and a rendered posterior\n        beside it would make the artifact contradict itself.\n    prior_supplied_by: who supplied the prior, when one was.")
