// GENERATED FROM schema/derivation.schema.json -- DO NOT EDIT.
// Regenerate with `make contract`. A CI job regenerates and fails on a diff.

import { z } from "zod";

export const ClaimVerdictSchema = z.enum(["supported","contradicted","unverifiable","insufficient_data"]).describe("The categorical finding about a claim.\n\nDeliberately about the *match structure* rather than about probability. The\nlikelihood ratio is a separate quantity attached alongside; deriving a verdict\nfrom it would conflate \"what the chain shows\" with \"how much that is worth\",\nwhich the verification layer keeps strictly apart.")

export const DerivationKindSchema = z.enum(["claim","verdict","proposition","evidence","quantity_k","quantity_p","likelihood_ratio","sensitivity","verbal_band","posterior","assumption","caveat","because"]).describe("What one node of the derivation is.\n\nThe kinds are the *vocabulary of the argument*, not of the data: ``QUANTITY_K`` and\n``QUANTITY_P`` are separate from ``EVIDENCE`` because a measured number and the finding\nthat produced it are different claims, and ``BECAUSE`` exists so the refusal case has a\nnode of its own rather than being smuggled into a verdict's label.")

export const VerbalScaleSchema = z.enum(["none","slight","moderate","moderately strong","strong","very strong"]).describe("Belief in a proposition, on the ENFSI verbal scale.\n\nTaken from the appendix of the *ENFSI Guideline for Evaluative Reporting in\nForensic Science* (2015). The guideline treats the verbal scale as optional\nand jurisdiction-dependent and prefers the numeric ratio where one can be\ngiven, so the boundaries behind these bands are configurable -- see\n:class:`~chainlens.verify.scale.VerbalThresholds` -- and these labels are the\ndefault rather than a universal standard.")

export const DetailKindSchema = z.enum(["string","int","float","bool","list","null"]).describe("The six scalars a detail value can be.\n\nSix, not \"any\": a value that is none of these is refused rather than stringified,\nbecause stringifying is how a nested object becomes text that reads like a finding.\n\n``INT`` carries its value as a **decimal string**, for the reason\n:data:`BaseUnits` sets out: a detail may be an amount, and an amount in a browser is a\ndouble. A detail is free-form, so there is no field type to hang the rule on and it\nbelongs to the kind instead.")

export const DetailEntrySchema = z.object({ "key": z.string(), "kind": DetailKindSchema, "unit": z.union([z.string(), z.null()]).default(null), "value": z.union([z.string(), z.number().int(), z.number(), z.boolean(), z.array(z.string()), z.null()]).default(null) }).strict().describe("One labelled fact, in a form two languages can render identically.\n\nAttributes:\n    key: the checker's own key, unchanged.\n    kind: which scalar this is, so a renderer needs no narrowing.\n    value: the value, or ``None`` when ``kind`` is ``null``.\n    unit: an optional unit for a number, e.g. ``\"base units\"``.")

export const GraphRefKindSchema = z.enum(["node","edge"]).describe("What a reference points at. An edge is addressable here, unlike in the flow view.")

export const GraphRefSchema = z.object({ "exists": z.union([z.boolean(), z.null()]).default(null), "key": z.string(), "kind": GraphRefKindSchema, "note": z.union([z.string(), z.null()]).default(null) }).strict().describe("A pointer into a ledger document, which may or may not hold it.\n\nAttributes:\n    kind: whether the reference names a node or an edge.\n    key: the node or edge key. Node keys are ``address:``/``tx:``/``unparsed:``;\n        edge keys are ``{txid}:in|out|tok|int:{index}``.\n    exists: whether it was found in the document it was resolved against. ``None``\n        means nobody has looked — which is not the same as absent, and a front end\n        should offer to fetch rather than reporting nothing there.\n    note: why it was not found, when something knows.")

export const DerivationNodeSchema: z.ZodType = z.lazy(() => z.object({ "band": z.union([VerbalScaleSchema, z.null()]).default(null), "children": z.array(DerivationNodeSchema).default([]), "detail": z.array(DetailEntrySchema).default([]), "graph_refs": z.array(GraphRefSchema).default([]), "id": z.string(), "kind": DerivationKindSchema, "label": z.string(), "summary": z.union([z.string(), z.null()]).default(null), "unit": z.union([z.string(), z.null()]).default(null), "value": z.union([z.number(), z.null()]).default(null) }).strict().describe("One step of a derivation, and everything a reader needs to disagree with it.\n\nAttributes:\n    id: a path-derived identifier, stable across runs — ``claim``,\n        ``claim/evidence/0`` — so a renderer can key nodes and a fixture can be\n        compared.\n    kind: what this step is.\n    label: the short thing to show on the node. Written here rather than in the\n        renderer, because a label the renderer invents is a claim the library did not\n        make.\n    summary: a sentence, when the label is not enough.\n    detail: labelled facts, in the tagged form a second language can render.\n    value: the number this step is about, when it is about one.\n    unit: what that number is counted in.\n    band: the verbal band, on the band and posterior nodes.\n    graph_refs: the ledger nodes and edges this step rests on. Carried whether or not\n        they resolve — see :class:`~chainlens.models.wire.GraphRef`.\n    children: the steps below this one."));

export const DerivationDocumentSchema = z.object({ "claim_id": z.string(), "claim_quote": z.string(), "has_ratio": z.boolean().default(false), "limitations": z.string(), "method": z.string(), "prior_supplied_by": z.union([z.string(), z.null()]).default(null), "root": DerivationNodeSchema, "schema_version": z.number().int().default(1), "verdict": ClaimVerdictSchema }).strict().describe("One finding's derivation, as a document a front end can render.\n\nAttributes:\n    schema_version: the contract version. Both ends refuse an unknown major.\n    claim_id: derived from the claim, so a graph overlay can group findings by claim.\n    claim_quote: the verbatim span the claim was read from, so a reader can see what is\n        being adjudicated without the graph.\n    verdict: the categorical finding, repeated at the root because it is the thing the\n        tree explains.\n    method: which checker produced the verdict.\n    has_ratio: whether a likelihood ratio was reported. The tree's shape differs, and a\n        renderer should not have to walk it to find out.\n    root: the tree.\n    limitations: the standing caveats. **Replaced when a prior was supplied**, because\n        the standard text says the library reports no posterior and a rendered posterior\n        beside it would make the artifact contradict itself.\n    prior_supplied_by: who supplied the prior, when one was.")
