// GENERATED FROM schema/overlay.schema.json -- DO NOT EDIT.
// Regenerate with `make contract`. A CI job regenerates and fails on a diff.

import { z } from "zod";

export const DetailKindSchema = z.enum(["string","int","float","bool","list","null"]).describe("The six scalars a detail value can be.\n\nSix, not \"any\": a value that is none of these is refused rather than stringified,\nbecause stringifying is how a nested object becomes text that reads like a finding.\n\n``INT`` carries its value as a **decimal string**, for the reason\n:data:`BaseUnits` sets out: a detail may be an amount, and an amount in a browser is a\ndouble. A detail is free-form, so there is no field type to hang the rule on and it\nbelongs to the kind instead.")

export const DetailEntrySchema = z.object({ "key": z.string(), "kind": DetailKindSchema, "unit": z.union([z.string(), z.null()]).default(null), "value": z.union([z.string(), z.number().int(), z.number(), z.boolean(), z.array(z.string()), z.null()]).default(null) }).strict().describe("One labelled fact, in a form two languages can render identically.\n\nAttributes:\n    key: the checker's own key, unchanged.\n    kind: which scalar this is, so a renderer needs no narrowing.\n    value: the value, or ``None`` when ``kind`` is ``null``.\n    unit: an optional unit for a number, e.g. ``\"base units\"``.")

export const GraphRefKindSchema = z.enum(["node","edge"]).describe("What a reference points at. An edge is addressable here, unlike in the flow view.")

export const GraphRefSchema = z.object({ "exists": z.union([z.boolean(), z.null()]).default(null), "key": z.string(), "kind": GraphRefKindSchema, "note": z.union([z.string(), z.null()]).default(null) }).strict().describe("A pointer into a ledger document, which may or may not hold it.\n\nAttributes:\n    kind: whether the reference names a node or an edge.\n    key: the node or edge key. Node keys are ``address:``/``tx:``/``unparsed:``;\n        edge keys are ``{txid}:in|out|tok|int:{index}``.\n    exists: whether it was found in the document it was resolved against. ``None``\n        means nobody has looked — which is not the same as absent, and a front end\n        should offer to fetch rather than reporting nothing there.\n    note: why it was not found, when something knows.")

export const EvidenceKindSchema = z.enum(["finding","label","entity","warning","annotation"]).describe("Where a piece of evidence came from.\n\nThe first four are computed by the library and the last is asserted by a person, and\nthey are separate members so a renderer cannot accidentally style them alike.")

export const ProvenanceSchema = z.object({ "cache_mode": z.union([z.string(), z.null()]).default(null), "cached": z.boolean().default(false), "confidence": z.union([z.number().gte(0).lte(1), z.null()]).default(null), "endpoint": z.union([z.string(), z.null()]).default(null), "fetched_at": z.string().datetime({ offset: true }), "heuristic": z.union([z.string(), z.null()]).default(null), "provider": z.string(), "provider_version": z.union([z.string(), z.null()]).default(null), "request_id": z.union([z.string(), z.null()]).default(null) }).strict().describe("Where a retrieved fact came from.\n\n``fetched_at`` is always timezone-aware. ``cached`` and ``cache_mode`` record\nwhether the value came from the HTTP cache and in which mode, so a replay or\noffline run is never mistaken for a live observation.")

export const LabelSourceSchema = z.enum(["provider","user","heuristic","imported"]).describe("Provenance of a label attached to an address or entity.\n\nProvenance is what separates \"an exchange confirmed this address\" from \"a\nheuristic guessed it\", so it is recorded on every label.")

export const EvidenceItemSchema = z.object({ "claim_id": z.union([z.string(), z.null()]).default(null), "confidence": z.union([z.number().gte(0).lte(1), z.null()]).default(null), "detail": z.array(DetailEntrySchema).default([]), "graph_refs": z.array(GraphRefSchema).default([]), "kind": EvidenceKindSchema, "provenance": z.array(ProvenanceSchema).default([]), "source": z.union([LabelSourceSchema, z.null()]).default(null), "summary": z.string() }).strict().describe("One thing known about a node or an edge.\n\nAttributes:\n    kind: where it came from.\n    summary: a sentence for a reader.\n    detail: labelled facts in the tagged form a second language can render.\n    claim_id: the claim this belongs to, when it came from a finding, so the graph and\n        a derivation can highlight each other.\n    graph_refs: everything this item touches, with ``exists`` resolved against the\n        document it was joined onto.\n    provenance: where the fact came from, when a provider supplied it.\n    source: whose assertion it is, when it is a label of any kind.\n    confidence: only ever a *heuristic's* own confidence, never a declared one — see the\n        annotation model, which has no such field.")

export const OverlayDocumentSchema = z.object({ "by_edge": z.record(z.string(), z.array(EvidenceItemSchema)).optional(), "by_node": z.record(z.string(), z.array(EvidenceItemSchema)).optional(), "claim_refs": z.record(z.string(), z.array(GraphRefSchema)).optional(), "schema_version": z.number().int().default(1), "unjoined": z.array(GraphRefSchema).default([]), "warnings": z.array(z.string()).default([]) }).strict().describe("Everything known about a graph's nodes and edges, keyed the way the graph is.\n\nAttributes:\n    schema_version: the contract version.\n    by_node: node key to the evidence about it, in a stable order.\n    by_edge: edge key to the evidence about it.\n    claim_refs: claim id to everything that claim touches, so selecting a claim in one\n        view can highlight it in the other.\n    unjoined: references that resolved to nothing here. **Reported, never dropped**: a\n        claim about an address outside the walked window would otherwise vanish, and \"we\n        hold evidence about something you cannot see — deepen the walk\" is both true and\n        actionable.\n    warnings: anything that qualified the join.")
