"""The golden document: one walk that exercises every shape the contract can carry.

Generated by running the real walk over a purpose-built fixture rather than assembled by
hand, so it is a regression detector as well as a sample. A field that changes shape, a
node kind that stops being emitted, an edge role that starts collapsing — all of them show
up as a diff in the committed JSON.

It lives in the test tree rather than in the package because it is scaffolding for tests
and for the TypeScript validation suite, not something a user of the library needs.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import anyio

from chainlens.ledger.schema import strict_dumps
from chainlens.ledger.walk import walk_ledger
from chainlens.models.enums import AssetKind, Chain, FlowVia
from chainlens.models.ledger import LedgerGraph, LedgerPolicy
from chainlens.models.primitives import AssetRef
from chainlens.testing.factories import btc_transaction, eth_transaction, inp, out, transfer
from chainlens.testing.in_memory import InMemoryProvider

#: A fixed timestamp for every fixture document. Truncating the real one is not enough:
#: two runs a second apart would differ, and a fixture that changes whenever it is
#: regenerated cannot be compared against its committed copy.
FIXTURE_INSTANT = datetime(2026, 1, 1, tzinfo=UTC)

HERE = Path(__file__).resolve().parent
FIXTURE_PATH = HERE / "fixtures" / "graph-document.json"

MINER, CAROL, ALICE, BOB, DAVE, MALLORY = (
    "1MinerAddr",
    "1CarolAddr",
    "1AliceAddr",
    "1BobAddr",
    "1DaveAddr",
    "1MalloryAddr",
)

#: A token with a contract, and one without — the second is the case that would otherwise
#: collapse two different tokens into one indistinguishable edge.
DAI = AssetRef(
    chain=Chain.ETHEREUM,
    kind=AssetKind.ERC20,
    symbol="DAI",
    decimals=18,
    contract="0x6b175474e89094c44da98b954eedeac495271d0f",
)


def _bitcoin_provider() -> InMemoryProvider:
    """Every shape the UTXO path can produce, in two hops."""
    return InMemoryProvider(
        chain=Chain.BITCOIN,
        transactions=[
            # Minted value: a transaction node with no input edges.
            btc_transaction("cb0", [out(0, CAROL, 50_000)], is_coinbase=True, block_height=1),
            # Carol pays Alice, with change back to Carol — a flagged, kept change edge.
            btc_transaction(
                "tx1",
                [out(0, ALICE, 30_000), out(1, CAROL, 19_500)],
                [inp(0, CAROL, 50_000, prev_txid="cb0", prev_vout=0)],
                block_height=2,
                fee=500,
            ),
            # An OP_RETURN-shaped output: real value, no address, kept rather than dropped.
            btc_transaction(
                "tx2",
                [out(0, BOB, 20_000), out(1, None, 0)],
                [inp(0, ALICE, 20_000, prev_txid="tx1", prev_vout=0)],
                block_height=3,
            ),
            # Alice co-funds with Dave: a CoinJoin by the library's own rule, and the case
            # where reading a flow *through* the transaction is most wrong.
            btc_transaction(
                "tx3",
                [out(0, MALLORY, 5_000), out(1, DAVE, 5_000), out(2, BOB, 5_000)],
                [
                    inp(0, ALICE, 5_000),
                    inp(1, DAVE, 5_000),
                    inp(2, CAROL, 5_000),
                ],
                block_height=4,
            ),
            # A value the provider never recorded, which stays unknown rather than zero.
            btc_transaction(
                "tx4",
                [out(0, DAVE, 900)],
                [inp(0, BOB, None, prev_txid="unindexed", prev_vout=0)],
                block_height=5,
            ),
        ],
    )


def _evm_provider() -> InMemoryProvider:
    """The EVM path: a token movement, an internal transfer, and a second token."""
    moved = transfer(
        "0xcontract",
        "0xbbb",
        10**17,
        txid="0xe1",
        chain=Chain.ETHEREUM,
        via=FlowVia.INTERNAL,
        index=0,
    )
    return InMemoryProvider(
        chain=Chain.ETHEREUM,
        transactions=[
            eth_transaction(
                "0xe1", "0xaaa", "0xcontract", value=10**18, fee=21_000, block_height=9
            ).model_copy(update={"internal_transfers": (moved,)})
        ],
        token_transfers=[
            transfer(
                "0xaaa",
                "0xccc",
                500,
                txid="0xe1",
                chain=Chain.ETHEREUM,
                via=FlowVia.ERC20,
                asset=DAI,
                index=1,
            ),
        ],
    )


async def _bitcoin_document() -> LedgerGraph:
    return await walk_ledger(
        _bitcoin_provider(),
        seed_address=ALICE,
        policy=LedgerPolicy(max_depth=2, max_nodes=40, max_edges=40, max_fan_out=2),
    )


async def _evm_document() -> LedgerGraph:
    return await walk_ledger(
        _evm_provider(),
        seed_address="0xaaa",
        policy=LedgerPolicy(max_depth=1, max_nodes=30, max_edges=30),
    )


async def _empty_document() -> LedgerGraph:
    """A seed with no history: the degenerate case a front end still has to render."""
    return await walk_ledger(
        InMemoryProvider(chain=Chain.BITCOIN, transactions=[]),
        seed_address="1NobodyAddr",
        policy=LedgerPolicy(max_depth=1),
    )


async def _truncated_document() -> LedgerGraph:
    """A walk cut short by its budget, which a front end must render as *partial*.

    The one fixture whose point is the ``truncated`` flag and a populated
    ``stop_reasons``: a graph that is small because we stopped looking has to be
    distinguishable from a graph that is genuinely small.
    """
    return await walk_ledger(
        _bitcoin_provider(),
        seed_address=ALICE,
        policy=LedgerPolicy(max_depth=3, max_nodes=5, max_edges=4),
    )


DOCUMENTS: dict[str, Any] = {
    "bitcoin": _bitcoin_document,
    "evm": _evm_document,
    "empty": _empty_document,
    "truncated": _truncated_document,
}


def render_all() -> str:
    """Every fixture document, as one strict-JSON file.

    One file rather than three so the TypeScript side has a single import, and because the
    interesting assertions are about the *set* of shapes — every node kind, every edge
    role, both amount statuses — rather than about any one document.

    ``generated_at`` and ``elapsed_seconds`` are cleared, because they differ per run and a
    fixture that changes every time it is regenerated cannot be compared to its committed
    copy.
    """
    documents: dict[str, Any] = {}
    for name, build in DOCUMENTS.items():
        document = anyio.run(build)
        stable = document.model_copy(
            update={"generated_at": FIXTURE_INSTANT, "elapsed_seconds": None}
        )
        documents[name] = json.loads(strict_dumps(stable))
    return (
        json.dumps({"schema_version": 1, "documents": documents}, indent=2, sort_keys=True) + "\n"
    )


if __name__ == "__main__":  # pragma: no cover - a regeneration helper, not a code path
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(render_all(), encoding="utf-8")
    print(f"wrote {FIXTURE_PATH}")
