"""The golden documents: every shape the front-end contract can carry.

Generated by running the real code over purpose-built fixtures rather than assembled by
hand, so these are regression detectors as well as samples. A field that changes shape, a
node kind that stops being emitted, an edge role that starts collapsing, a derivation step
that loses its terms — all of them show up as a diff in the committed JSON.

Two families, because the front end reads two documents: the **ledger** walks, and the
**derivations** built from verification findings. Between them they cover both shapes of
derivation, which matters because the no-ratio one is the normal case today.

This lives in the test tree rather than in the package because it is scaffolding for tests
and for the TypeScript validation suite, not something a user of the library needs.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import anyio

from chainlens.ledger.derive import derive_finding
from chainlens.ledger.schema import strict_dumps
from chainlens.ledger.walk import walk_ledger
from chainlens.models.base import LensModel
from chainlens.models.derive import DerivationDocument
from chainlens.models.enums import AssetKind, Chain, FlowVia
from chainlens.models.ledger import LedgerGraph, LedgerPolicy
from chainlens.models.primitives import AssetRef
from chainlens.providers.base import Provider
from chainlens.social.models import Post, ProvenanceStrength, SourceRef
from chainlens.testing.factories import btc_transaction, eth_transaction, inp, out, transfer
from chainlens.testing.in_memory import InMemoryProvider
from chainlens.verify.claims import ClaimElements
from chainlens.verify.engine import VerificationEngine
from chainlens.verify.likelihood import (
    ComponentEstimate,
    EstimatorMethod,
    NullModel,
    wilson_interval,
)
from chainlens.verify.schema import Claim, ClaimType, Extraction
from chainlens.verify.verdicts import RateEstimate

#: A fixed timestamp for every fixture document. Truncating the real one is not enough:
#: two runs a second apart would differ, and a fixture that changes whenever it is
#: regenerated cannot be compared against its committed copy.
FIXTURE_INSTANT = datetime(2026, 1, 1, tzinfo=UTC)

HERE = Path(__file__).resolve().parent
FIXTURE_PATH = HERE / "fixtures" / "graph-document.json"

#: Real addresses, not placeholders. The walk does not care — it never validates — but a
#: claim that names an invalid address cannot be priced, so the derivation fixtures would
#: silently collapse to the no-ratio shape and the half of the tree that matters most would
#: go untested. Checksums and all, so both documents point at the same nodes.
MINER = "1BitcoinEaterAddressDontSendf59kuE"
CAROL = "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
ALICE = "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2"
BOB = "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy"
DAVE = "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4"
MALLORY = "3P14159f73E4gFr7JterCCQh9QjiTjiZrG"

#: A token with a contract, and one without — the second is the case that would otherwise
#: collapse two different tokens into one indistinguishable edge.
DAI = AssetRef(
    chain=Chain.ETHEREUM,
    kind=AssetKind.ERC20,
    symbol="DAI",
    decimals=18,
    contract="0x6b175474e89094c44da98b954eedeac495271d0f",
)


def _bitcoin_provider() -> InMemoryProvider:
    """Every shape the UTXO path can produce, in two hops."""
    return InMemoryProvider(
        chain=Chain.BITCOIN,
        transactions=[
            # Minted value: a transaction node with no input edges.
            btc_transaction("cb0", [out(0, CAROL, 50_000)], is_coinbase=True, block_height=1),
            # Carol pays Alice, with change back to Carol — a flagged, kept change edge.
            btc_transaction(
                "tx1",
                [out(0, ALICE, 30_000), out(1, CAROL, 19_500)],
                [inp(0, CAROL, 50_000, prev_txid="cb0", prev_vout=0)],
                block_height=2,
                fee=500,
            ),
            # An OP_RETURN-shaped output: real value, no address, kept rather than dropped.
            btc_transaction(
                "tx2",
                [out(0, BOB, 20_000), out(1, None, 0)],
                [inp(0, ALICE, 20_000, prev_txid="tx1", prev_vout=0)],
                block_height=3,
            ),
            # Alice co-funds with Dave: a CoinJoin by the library's own rule, and the case
            # where reading a flow *through* the transaction is most wrong.
            btc_transaction(
                "tx3",
                [out(0, MALLORY, 5_000), out(1, DAVE, 5_000), out(2, BOB, 5_000)],
                [
                    inp(0, ALICE, 5_000),
                    inp(1, DAVE, 5_000),
                    inp(2, CAROL, 5_000),
                ],
                block_height=4,
            ),
            # A value the provider never recorded, which stays unknown rather than zero.
            btc_transaction(
                "tx4",
                [out(0, DAVE, 900)],
                [inp(0, BOB, None, prev_txid="unindexed", prev_vout=0)],
                block_height=5,
            ),
        ],
    )


def _evm_provider() -> InMemoryProvider:
    """The EVM path: a token movement, an internal transfer, and a second token."""
    moved = transfer(
        "0xcontract",
        "0xbbb",
        10**17,
        txid="0xe1",
        chain=Chain.ETHEREUM,
        via=FlowVia.INTERNAL,
        index=0,
    )
    return InMemoryProvider(
        chain=Chain.ETHEREUM,
        transactions=[
            eth_transaction(
                "0xe1", "0xaaa", "0xcontract", value=10**18, fee=21_000, block_height=9
            ).model_copy(update={"internal_transfers": (moved,)})
        ],
        token_transfers=[
            transfer(
                "0xaaa",
                "0xccc",
                500,
                txid="0xe1",
                chain=Chain.ETHEREUM,
                via=FlowVia.ERC20,
                asset=DAI,
                index=1,
            ),
        ],
    )


async def _bitcoin_document() -> LedgerGraph:
    return await walk_ledger(
        _bitcoin_provider(),
        seed_address=ALICE,
        policy=LedgerPolicy(max_depth=2, max_nodes=40, max_edges=40, max_fan_out=2),
    )


async def _evm_document() -> LedgerGraph:
    return await walk_ledger(
        _evm_provider(),
        seed_address="0xaaa",
        policy=LedgerPolicy(max_depth=1, max_nodes=30, max_edges=30),
    )


async def _empty_document() -> LedgerGraph:
    """A seed with no history: the degenerate case a front end still has to render."""
    return await walk_ledger(
        InMemoryProvider(chain=Chain.BITCOIN, transactions=[]),
        seed_address="1NobodyAddr",
        policy=LedgerPolicy(max_depth=1),
    )


async def _truncated_document() -> LedgerGraph:
    """A walk cut short by its budget, which a front end must render as *partial*.

    The one fixture whose point is the ``truncated`` flag and a populated
    ``stop_reasons``: a graph that is small because we stopped looking has to be
    distinguishable from a graph that is genuinely small.
    """
    return await walk_ledger(
        _bitcoin_provider(),
        seed_address=ALICE,
        policy=LedgerPolicy(max_depth=3, max_nodes=5, max_edges=4),
    )


DOCUMENTS: dict[str, Any] = {
    "bitcoin": _bitcoin_document,
    "evm": _evm_document,
    "empty": _empty_document,
    "truncated": _truncated_document,
}


class _Pricing:
    """An estimator that prices a band by its width.

    A stub rather than a real one, because no estimator ships: the window-transfers
    capability it needs is unbuilt. It exists here so the ratio branch of a derivation has a
    fixture at all — otherwise the half of the tree that matters most would be untested
    against a real document until that capability lands.
    """

    async def estimate(self, elements: ClaimElements, *, provider: Provider) -> RateEstimate | None:
        band = elements.band
        wider = 1 + (band.tolerance / band.nominal if band and band.nominal else 0)
        lower, upper = wilson_interval(3, 30_000)
        return RateEstimate(
            component=ComponentEstimate(
                value=1e-4 * wider,
                successes=3,
                trials=30_000,
                ci_lower=lower,
                ci_upper=upper,
                method=EstimatorMethod.EMPIRICAL_JOINT,
                population="the sender's own out-of-window transfers",
            ),
            null_model=NullModel.WITHIN_SENDER,
        )


async def _no_ratio_derivation() -> DerivationDocument:
    """The normal shape: a verdict, its evidence, and why no number is reported."""
    engine = VerificationEngine(_bitcoin_provider())
    report = await engine.verify_post(_claim_post(), _claim_extraction())
    return derive_finding(report.findings[0])


async def _with_ratio_derivation() -> DerivationDocument:
    """The full shape, including a posterior — which exists only because a prior was given."""
    engine = VerificationEngine(_bitcoin_provider(), estimator=_Pricing())
    report = await engine.verify_post(_claim_post(), _claim_extraction())
    return derive_finding(report.findings[0], prior=1 / 1000, prior_supplied_by="the fixture")


#: The claim the derivation fixtures adjudicate, and it is about a transfer the ledger
#: fixture actually contains — carol paying alice in ``tx1``. A claim nothing matches would
#: teach the fixture nothing about the shape a verdict-producing derivation takes.
CLAIM_QUOTE = "carol moved ~30,000 sats to alice"


def _claim_post() -> Post:
    return Post(
        id="fixture-post",
        text=CLAIM_QUOTE,
        source=SourceRef(strength=ProvenanceStrength.PRINTOUT, captured_at=FIXTURE_INSTANT),
    )


def _claim_extraction() -> Extraction:
    return Extraction(
        claims=(
            Claim(
                type=ClaimType.TRANSFER,
                quote=CLAIM_QUOTE,
                addresses=(CAROL, ALICE),
                # Hedged, so the tolerance sweep has something to vary. An exactly-stated
                # amount produces variants that are all identical, and a sweep that varies
                # nothing is reported as though it had tested something.
                amount_text="~30,000 sats",
            ),
        )
    )


#: Derivations, keyed the way the fixture file keys them.
DERIVATIONS: dict[str, Any] = {
    "no_ratio": _no_ratio_derivation,
    "with_ratio": _with_ratio_derivation,
}


#: Anything that reads as an instant, wherever it appears in a document. Provenance
#: timestamps are recorded at fetch time and so differ on every run, in the middle of
#: otherwise stable evidence — which is why pinning only the document's own ``generated_at``
#: was not enough.
_TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}")


def _pin_timestamps(value: Any) -> Any:
    """Replace every instant with the fixture instant, recursively."""
    if isinstance(value, dict):
        return {key: _pin_timestamps(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_pin_timestamps(item) for item in value]
    if isinstance(value, str) and _TIMESTAMP.match(value):
        return FIXTURE_INSTANT.isoformat()
    return value


def _stable(document: LensModel) -> dict[str, Any]:
    """A document with its run-dependent fields pinned, as a plain dict.

    ``generated_at`` and ``elapsed_seconds`` say when the walk ran, and a provenance
    ``fetched_at`` says when a request was made. All three differ per run, and a fixture that
    changes whenever it is regenerated cannot be compared against its committed copy — which
    is the whole point of committing one.
    """
    pinned: dict[str, Any] = {"generated_at": FIXTURE_INSTANT}
    if "elapsed_seconds" in document.__class__.model_fields:
        pinned["elapsed_seconds"] = None
    stable: dict[str, Any] = json.loads(strict_dumps(document.model_copy(update=pinned)))
    pinned_document: dict[str, Any] = _pin_timestamps(stable)
    return pinned_document


def render_all() -> str:
    """Every fixture document, as one strict-JSON file.

    One file rather than several so the TypeScript side has a single import, and because the
    interesting assertions are about the *set* of shapes — every node kind, every edge role,
    both amount statuses, both derivation shapes — rather than about any one document.
    """
    ledgers: dict[str, Any] = {}
    for name, build in DOCUMENTS.items():
        ledgers[name] = _stable(anyio.run(build))

    derivations: dict[str, Any] = {}
    for name, build in DERIVATIONS.items():
        derivations[name] = _stable(anyio.run(build))

    return (
        json.dumps(
            {"schema_version": 1, "ledgers": ledgers, "derivations": derivations},
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


if __name__ == "__main__":  # pragma: no cover - a regeneration helper, not a code path
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(render_all(), encoding="utf-8")
    print(f"wrote {FIXTURE_PATH}")
