#!/usr/bin/env python3
"""Render this package's own data into the shipped card, or check that it is current.

    python tools/gen_shipped_data.py            # write the artefact
    python tools/gen_shipped_data.py --check    # report staleness, write nothing

**Why presets and not labels, which is the asymmetry worth reading.** A card entry for a preset
is a :class:`~chainlens.presets.records.Preset` — *the same type the YAML produces* — so rendering
one into the shipped card is lossless and the YAML stays the hand-edited source. A card entry for
a **label** is not: `labels/data/events.yaml` carries a `corroboration` beside each record, what
the chain showed when somebody looked, and the file's own header calls that the half that makes
this chain analysis rather than a literature review. A card entry has no way to carry one, because
a holder cannot observe the chain at load time — so rendering the shipped labels would *drop* the
field that carries the weight. The two are therefore two kinds with an overlap, and
`labels/provider.py::LocalLabelProvider` overlays them where the answer is given.

**The alternative to rendering was for `SHIPPED` to carry nothing and `presets/data/` to be read
at use.** That leaves two objects where the card's own claim is that there is one, and it means a
caller holding a card has to know which of the two to look in. The generator is the smaller cost.

The artefact is `src/chainlens/_shipped_card.py` rather than a module under `chainlens.keycard`,
because `chainlens.keycard` is a *module* and not a package — a fact worth knowing before reaching
for a submodule path that cannot exist.

Usage:
    python tools/gen_shipped_data.py            # write
    python tools/gen_shipped_data.py --check    # report staleness
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

PRESET_DIR = ROOT / "src" / "chainlens" / "presets" / "data"
ARTEFACT = ROOT / "src" / "chainlens" / "_shipped_card.py"


def _presets() -> list[dict[str, Any]]:
    """Every shipped preset, in a stable order, as plain data.

    Sorted by name rather than by filename so that a rename is a change to one place rather than a
    reordering of the artefact — the same reason the vocabulary table's order is stated.
    """
    out: list[dict[str, Any]] = []
    for path in sorted(PRESET_DIR.glob("*.yaml")):
        loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(loaded, dict):
            raise SystemExit(f"{path}: expected a mapping, got {type(loaded).__name__}")
        out.append(loaded)
    return sorted(out, key=lambda entry: entry["name"])


def render() -> str:
    """The shipped data, as a module the card imports.

    Python literals rather than a JSON blob read at import: the card is imported on every run,
    and a module that opened a file at import time would be doing I/O to answer a question about
    a chain — the kind of hidden cost this package avoids everywhere.
    """
    rows = [
        "    Preset(\n"
        f"        name={entry['name']!r},\n"
        f"        description={entry.get('description', '')!r},\n"
        f"        chain=Chain({entry['chain']!r}),\n"
        f"        source={entry['source']!r},\n"
        f"        funding_address={entry.get('funding_address')!r},\n"
        f"        rates=({_rates(entry.get('rates', []))}),\n"
        f"        allocation_dataset={entry.get('allocation_dataset')!r},\n"
        f"        notes={tuple(entry.get('notes', []))!r},\n"
        "    ),"
        for entry in _presets()
    ]
    body = "\n".join(rows)
    return f'''"""GENERATED FILE - DO NOT EDIT BY HAND.

Generated by `tools/gen_shipped_data.py` from `src/chainlens/presets/data/*.yaml`.

The shipped presets, in the card, so that the library's data and a holder's data are one object
rather than two that must be looked in separately. **The YAML under `presets/data/` is the
hand-edited source**; edit that and run `make shipped-card`.

Only presets are rendered, and the asymmetry with labels is deliberate: a card entry for a preset
is the same `Preset` the YAML produces, so nothing is lost, where a shipped *label* carries a
corroboration a card entry has no way to hold.

Edit the YAML and run `make shipped-card`. `tests/keycard/test_shipped.py` fails when this file is
stale, so it cannot drift from its source silently.
"""

from __future__ import annotations

from typing import Final

from chainlens.models.enums import Chain
from chainlens.presets.records import Preset, RateTier

__all__ = ["SHIPPED_PRESETS"]


SHIPPED_PRESETS: Final[tuple[Preset, ...]] = (
{body}
)
'''


def _rates(rows: list[dict[str, Any]]) -> str:
    """The rate tiers, as `RateTier` constructions."""
    if not rows:
        return ""
    inner = "".join(
        f"\n            RateTier(rate={row['rate']!r}, note={row.get('note', '')!r}),"
        for row in rows
    )
    return inner + "\n        "


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report staleness, write nothing")
    parser.add_argument("--quiet", action="store_true", help="only report problems")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        if not ARTEFACT.exists() or ARTEFACT.read_text(encoding="utf-8") != rendered:
            print(
                "gen_shipped_data: stale; run `make shipped-card` and commit the result:\n  "
                + ARTEFACT.relative_to(ROOT).as_posix(),
                file=sys.stderr,
            )
            return 1
        if not args.quiet:
            print(f"gen_shipped_data: {ARTEFACT.relative_to(ROOT).as_posix()} matches its source")
        return 0

    ARTEFACT.parent.mkdir(parents=True, exist_ok=True)
    ARTEFACT.write_text(rendered, encoding="utf-8")
    if not args.quiet:
        print("wrote", ARTEFACT.relative_to(ROOT).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
