"""GENERATED FILE - DO NOT EDIT BY HAND.

Generated by `tools/gen_vocabulary.py` from `specs/vocabulary/vocabulary.toml`.

The rows of the vocabulary table, in the order the table writes them. **That order is the
dimension basis** - `lean/Chainlens/Dim.lean` reads a dimension as a weight per row by
position - so reordering the table permutes every exponent vector at once and is a change to
the calculus rather than a tidy-up.

Edit the table and run `make vocabulary`. `tests/vocabulary/test_the_table.py` fails when
this file is stale, so it cannot drift from the table silently.
"""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final, NamedTuple

__all__ = [
    "ASSETS",
    "BY_BASE58CHECK_VERSION",
    "BY_BECH32_HRP",
    "BY_CHAIN",
    "BY_ID",
    "AssetRow",
]


class AssetRow(NamedTuple):
    """One row of the vocabulary table.

    Attributes:
        id: the row's identity, and what belongs on the wire where a symbol would.
        chain: the chain it is the native asset of, as `Chain` spells it.
        symbol: the ticker a person writes. Not an identity - two chains may share one.
        decimals: how many decimal places one whole unit has.
        families: the address families this library validates for the chain.
        base58check_versions: the version bytes that identify this chain within base58check —
            P2PKH then P2SH. Empty when the row does not name that family, and **two chains may
            share a byte**: bitcoin and bitcoin cash both use `0` and `5`, because the chains
            forked and kept the format. That is a fact about them and not a gap here.
        bech32_hrp: the human-readable part that identifies this chain within bech32, or `None`
            when it has no bech32 form.
        note: the table's prose about the row, empty when it has none.
    """

    id: str
    chain: str
    symbol: str
    decimals: int
    families: tuple[str, ...]
    base58check_versions: tuple[int, ...]
    bech32_hrp: str | None
    note: str


ASSETS: Final[tuple[AssetRow, ...]] = (
    AssetRow(
        id="btc",
        chain="bitcoin",
        symbol="BTC",
        decimals=8,
        families=('base58check', 'bech32'),
        base58check_versions=(0, 5),
        bech32_hrp='bc',
        note="The native coin of Bitcoin, and the only asset this library can price from a post.",
    ),
    AssetRow(
        id="tbtc",
        chain="bitcoin_testnet",
        symbol="BTC",
        decimals=8,
        families=('base58check', 'bech32'),
        base58check_versions=(111, 196),
        bech32_hrp='tb',
        note="Testnet bitcoin, which shares the mainnet ticker: the symbol is a display convention and the chain is what tells them apart, so `(chain, asset)` is the identity and not `symbol`.",
    ),
    AssetRow(
        id="ltc",
        chain="litecoin",
        symbol="LTC",
        decimals=8,
        families=('base58check', 'bech32'),
        base58check_versions=(48, 50),
        bech32_hrp='ltc',
        note="No provider in this tree serves Litecoin yet; the row exists so its decimals are not written down elsewhere.",
    ),
    AssetRow(
        id="doge",
        chain="dogecoin",
        symbol="DOGE",
        decimals=8,
        families=('base58check',),
        base58check_versions=(30, 22),
        bech32_hrp=None,
        note="No provider in this tree serves Dogecoin yet. Dogecoin has no bech32 address form.",
    ),
    AssetRow(
        id="bch",
        chain="bitcoin_cash",
        symbol="BCH",
        decimals=8,
        families=('base58check',),
        base58check_versions=(0, 5),
        bech32_hrp=None,
        note="No provider in this tree serves Bitcoin Cash yet. Its cashaddr form is deliberately not listed: `families` names what this library can validate, and nothing here implements it.",
    ),
    AssetRow(
        id="eth",
        chain="ethereum",
        symbol="ETH",
        decimals=18,
        families=('eip55',),
        base58check_versions=(),
        bech32_hrp=None,
        note="The native coin of Ethereum. `families` is EIP-55 alone because a lowercase `0x` address carries no checksum to check; `codec/eth_address.py` accepts one and the notes identifier layer is where the absence of a checksum is recorded as a caveat rather than a failure.",
    ),
)

_ROW_0 = ASSETS[0]
_ROW_1 = ASSETS[1]
_ROW_2 = ASSETS[2]
_ROW_3 = ASSETS[3]
_ROW_4 = ASSETS[4]
_ROW_5 = ASSETS[5]


#: The rows that claim a version byte, keyed by it. **A list**, because bitcoin and bitcoin cash
#: share theirs — an address on that byte is genuinely two chains' and a caller is entitled to
#: know rather than being handed whichever row came first.
BY_BASE58CHECK_VERSION: Final[Mapping[int, tuple[AssetRow, ...]]] = MappingProxyType(
    {
    0: (_ROW_0, _ROW_4,),
    5: (_ROW_0, _ROW_4,),
    22: (_ROW_3,),
    30: (_ROW_3,),
    48: (_ROW_2,),
    50: (_ROW_2,),
    111: (_ROW_1,),
    196: (_ROW_1,),
    }
)

#: The rows that claim a bech32 human-readable part, keyed by it. A list for the same reason,
#: though no two shipped rows share one today: the type is what makes a shared one visible rather
#: than silently resolved.
BY_BECH32_HRP: Final[Mapping[str, tuple[AssetRow, ...]]] = MappingProxyType(
    {
    "bc": (_ROW_0,),
    "ltc": (_ROW_2,),
    "tb": (_ROW_1,),
    }
)

BY_ID: Final[Mapping[str, AssetRow]] = MappingProxyType(
    {
    "btc": _ROW_0,
    "tbtc": _ROW_1,
    "ltc": _ROW_2,
    "doge": _ROW_3,
    "bch": _ROW_4,
    "eth": _ROW_5,
    }
)

BY_CHAIN: Final[Mapping[str, AssetRow]] = MappingProxyType(
    {
    "bitcoin": _ROW_0,
    "bitcoin_testnet": _ROW_1,
    "litecoin": _ROW_2,
    "dogecoin": _ROW_3,
    "bitcoin_cash": _ROW_4,
    "ethereum": _ROW_5,
    }
)
